version: '3.8'
services:
  proximidade:
    container_name: suporte-proximidade
    build: .
    restart: on-failure
    ports:
      - "3232:3232"
    environment:
      - PORT=3000
      - DB_TYPE=mongo
      - PG_HOST=db
      - PG_USERNAME=mongodb
      - PG_PASSWORD=mongodb
      - PG_DB=mongodb
      - PG_PORT=5432
    depends_on:
      - db
  db:
    container_name: db_mongo
    image: "mongo:latest"
    ports:
      - 8080:8080
    volumes:
      - ./data:/data/db
